import type { Metadata } from 'next';
import { roboto } from '@/app/ui/fonts';
import './globals.css';
import { Summary } from './ui/Summary';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={'${roboto.className} antialiased'}>
        <div className='min-h-screen text-white lg:p-12 md:p-10 p-4  Parent bg-background'>

          <div className='flex space-y-[56px] lg:flex-row lg:space-x-[54px] lg:space-y-[0px] justify-center px-10'>
            <Summary title='Fritilaria' />
            <div>{children}</div>
          </div>
        </div>

      </body>
    </html>

  )
}
